# Generated by Django 6.0.3 on 2026-06-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('founder', 'Founder & CEO'), ('support', 'Support Staff'), ('head_stylist', 'Head Stylist')], default='Staff', max_length=100),
        ),
    ]
