# Generated by Django 6.0.3 on 2026-05-29 09:02

import customer.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('appointment_date', models.DateField()),
                ('time_slot', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending (awaiting confirmation)'), ('approved', 'Approved & confirm booking'), ('rejected', 'Rejected Appointment / Decline'), ('canceled', 'Canceled by Customer'), ('completed', 'Completed Appointment')], default='pending', max_length=20)),
                ('profile_picture', models.ImageField(blank=True, default='default_profile.jpg', null=True, upload_to=customer.utils.customer_profile_image_path)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
    ]
