# Generated by Django 6.0.3 on 2026-05-29 09:02

import django.utils.timezone
import staff.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('profile_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=staff.utils.staff_profile_image_path)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('hair stylist', 'Hair Stylist'), ('receptionist', 'Receptionist'), ('manager', 'Manager'), ('massage therapist', 'Massage Therapist'), ('nail technician', 'Nail Technician'), ('esthetician', 'Esthetician')], default='N/A', max_length=20)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
