# Generated by Django 6.0.3 on 2026-05-29 09:02

import admin_manager.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAppointmentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_time_slot', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, choices=[('customer_request', 'Customer Request'), ('busy_schedule', 'Busy Schedule'), ('found_another', 'Found Another Service Provider'), ('other', 'Other Reason'), ('admin_cancelled', 'Admin Cancelled'), ('no_show', 'Client did not show up')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(default='N/A', max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('admin_profile_image', models.ImageField(default='default_profile.jpg', upload_to=admin_manager.utils.admin_profile_image_path)),
            ],
        ),
    ]
