# Generated by Django 6.0.3 on 2026-05-29 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_manager', '0002_initial'),
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminappointmentapproval',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_canceled_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminappointmentapproval',
            name='customer_appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_approval', to='customer.customerappointment'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
