# Generated by Django 6.0.3 on 2026-06-06 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_updated_at_servicecategory_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'Service Category', 'verbose_name_plural': 'Service Categories'},
        ),
    ]
