# Generated by Django 6.0.3 on 2026-05-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Elite Saloon', help_text='The name of your business/site', max_length=100)),
                ('site_email', models.EmailField(default='admin@elitesaloon.com', help_text='Primary contact email', max_length=254)),
                ('site_logo', models.ImageField(blank=True, help_text='Upload your site logo (recommended size: 200x200px)', null=True, upload_to='site_logo/')),
                ('site_phonenumber', models.CharField(blank=True, default='1234567890', help_text='Contact phone number', max_length=20, null=True)),
                ('site_address', models.CharField(blank=True, default='Hamdan St, Abu Dhabi, UAE', help_text='Physical address', max_length=255, null=True)),
                ('site_description', models.TextField(blank=True, help_text='Brief description of your business', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
