# Generated by Django 6.0.3 on 2026-05-29 09:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('appointment', 'Appointment'), ('canceled_appointment', 'Canceled Appointment'), ('assigned_staff', 'Assigned Staff'), ('system', 'SYSTEM'), ('approved', 'Approved Appointment'), ('rejected', 'Rejected')], default='system', max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.URLField(blank=True, help_text='Optional link to redirect(e.g., appointments)', null=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Notifications',
                'ordering': ['-timestamp'],
            },
        ),
    ]
